#                                                                        #
# Default subroutes configuration for the Blog package                   #
#                                                                        #

-
  name: 'Comment actions'
  uriPattern:    'posts/{post}/comments/{@action}'
  defaults:
    '@controller': 'Comment'
  routeParts:
    post:
      objectType: TYPO3\Blog\Domain\Model\Post
      uriPattern: '{date:Y}/{date:m}/{date:d}/{title}'

-
  name: 'Single Post Actions'
  uriPattern:    'posts/{post}'
  defaults:
    '@controller': 'Post'
    '@action':     'show'
  routeParts:
    post:
      objectType: TYPO3\Blog\Domain\Model\Post
      uriPattern: '{date:Y}/{date:m}/{date:d}/{title}'

-
  name: 'Single Post Actions'
  uriPattern:    'posts/{post}/{@action}'
  defaults:
    '@controller': 'Post'
    '@action':     'show'
  routeParts:
    post:
      objectType: TYPO3\Blog\Domain\Model\Post
      uriPattern: '{date:Y}/{date:m}/{date:d}/{title}'

-
  name: 'Posts of a specific category'
  uriPattern:    'posts/category/{category}'
  defaults:
    '@controller': 'Post'
    '@action':     'index'
  routeParts:
    category:
      objectType: TYPO3\Blog\Domain\Model\Category

-
  name: 'Posts of a specific tag'
  uriPattern:    'posts/tag/{tag}'
  defaults:
    '@controller': 'Post'
    '@action':     'index'
  routeParts:
    tag:
      objectType: TYPO3\Blog\Domain\Model\Tag
      uriPattern: '{name}'


# Note: Pagination needs some special care due to the way widgets currently build URIs
-
  name: 'Posts Pagination'
  uriPattern:    'posts/page/{@widget_0.currentPage}'
  defaults:
    '@controller': 'Post'
    '@action':     'index'
    '@widget_0':
      '@controller':  ''
      '@package':     ''

-
  name: 'Posts Pagination - First page'
  uriPattern:    'posts'
  defaults:
    '@controller': 'Post'
    '@action':     'index'
    '@widget_0':
      '@controller':  ''
      '@package':     ''

-
  name: 'General Posts Actions'
  uriPattern:    'posts(/{@action})'
  defaults:
    '@controller': 'Post'
    '@action':     'index'

-
  name: 'Posts Feed'
  uriPattern:    'feeds/posts.atom.xml'
  defaults:
    '@controller': 'Post'
    '@action':     'index'
    '@format':     'atom.xml'

-
  name: 'Single Category Actions'
  uriPattern:    'categories/{category}/{@action}'
  defaults:
    '@controller': 'Category'
  routeParts:
    category:
      objectType: TYPO3\Blog\Domain\Model\Category

-
  name: 'General Category Actions'
  uriPattern:    'categories(/{@action})'
  defaults:
    '@controller': 'Category'
    '@action':     'index'

-
  name: 'Account actions'
  uriPattern: 'admin/account(/{@action})'
  defaults:
    '@controller': 'Account'
    '@action':     'edit'

-
  name: 'Blog actions'
  uriPattern: 'admin/blog(/{@action})'
  defaults:
    '@controller': 'Blog'
    '@action':     'edit'

-
  name: 'Admin Overview'
  uriPattern: 'admin'
  defaults:
    '@controller': 'Admin'
    '@action':     'index'

-
  name: 'Setup'
  uriPattern: 'admin/setup(/{@action})'
  defaults:
    '@controller': 'Setup'
    '@action':     'index'

-
  name: 'Authentication Actions'
  uriPattern: 'admin/authentication(/{@action})'
  defaults:
    '@controller': 'Login'
    '@action':     'index'

-
  name: 'Fallback rule'
  uriPattern:    ''
  defaults:
    '@controller': 'Post'
    '@action':     'index'
